trigger:
 branches:
   include:
     - feature
     - main 
schedules:
  - cron: "30 16 * * *"
    displayName: Nightly Terraform Destroy (10 PM IST)
    branches:
      include:
        - main
    always: true
    
pool: mahesh_pool

stages:
- stage: terraformBuild
  jobs:
  - job: TerraformBuild
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        backendServiceArm: 'new_infra'
        backendAzureRmStorageAccountName: 'stg23'
        backendAzureRmContainerName: 'cont23'
        backendAzureRmKey: 'devtfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        environmentServiceNameAzureRM: 'new_infra'
  
- stage: TerraformScan
  jobs:
    - job: TFSec
      displayName: TFSec
      steps:
    
      - task: tfsec@1
        continueOnError: True
        inputs:
          version: 'v1.26.0'
          dir: '''$(System.DefaultWorkingDirectory)/dev'''
  
    - job: TFlint
      displayName: TFLint
      steps:
        - script: |
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_windows.ps1 | powershell
            tflint --version
            cd $(System.DefaultWorkingDirectory)/dev
            tflint --init
            tflint
      
- stage: ManualValidation
  displayName: ManualValidation
  dependsOn: TerraformScan
  condition: always()
  pool: Server
  jobs:
    - job: ManualValidation
      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'mhosing24@outlook.com'
          approvers: 'mhosing24@outlook.com'
          instructions: 'Please review Terraform scan results and approve.'

- stage: Terraform_Build
  displayName: terraformApply
  dependsOn: ManualValidation
  condition: always()
  pool: mahesh_pool
  jobs:
    - job: 
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
          backendServiceArm: 'new_infra'
          backendAzureRmStorageAccountName: 'stg23'
          backendAzureRmContainerName: 'cont23'
          backendAzureRmKey: 'devtfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
          environmentServiceNameAzureRM: 'new_infra'
           
