trigger:
- feature
- main 

pool: mahesh_pool

stages:
- stage: 
  displayName: terraformBuild
  jobs:
  - job: 
    displayName: terraformInstall
    pool: mahesh_pool
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

  - job: 
    displayName: terraformInit
    steps:
    - task: TerraformTask@5
      displayName: terraformInit
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        backendServiceArm: 'new_infra'
        backendAzureRmStorageAccountName: 'stg23'
        backendAzureRmContainerName: 'cont23'
        backendAzureRmKey: 'devtfstate'

